### ISSUE TITLE
How to adjust context sizes and max response length with 8k tokens?

### ISSUE THREAD

**Issue by jujeongho0** [cannonLCK/wrtn_python#1]
Thank you for your code :)

I confirmed that the code is running normally, and in the meantime, a question arises, so I leave an issue. There is a problem that the answer is not normally output when an input sentence of about 1000 length is entered. It seems that the context size is too large, but I am wondering how to adjust the context size or max response to about 8k as you wrote in the readme.

**Comment by cannonLCK** [comment]
I've never tried to get a single request to approach 8k tokens, so I'm not sure about that. I suppose you could cut it down to a proper size and pass it to old_message.
